CREATE DATABASE SHOPPING_CART;
SELECT * FROM CUSTOMERS$;
SELECT * FROM orders$;
SELECT * FROM products$;
SELECT * FROM sales$;


  SELECT DISTINCT PRODUCT_TYPE FROM products$;


---- DATA EXPLORATION AND CLEANING----

 SELECT DISTINCT GENDER, COUNT(GENDER) "COUNT" FROM customers$ GROUP BY GENDER;
 SELECT MIN(AGE) MINIMUM_AGE, MAX(AGE) MAXIMUM_AGE FROM CUSTOMERS$;

 SELECT DISTINCT PRODUCT_TYPE FROM products$;


 CREATE PROCEDURE PRODUCT_CATEG 
 @PRODUCT_TYPE NVARCHAR(30)
 AS 
 SELECT DISTINCT PRODUCT_TYPE,PRODUCT_NAME FROM products$ WHERE PRODUCT_TYPE = @PRODUCT_TYPE
 GO

EXEC PRODUCT_CATEG  @PRODUCT_TYPE= 'SHIRT'
EXEC PRODUCT_CATEG  @PRODUCT_TYPE= 'TROUSERS'
EXEC PRODUCT_CATEG  @PRODUCT_TYPE= 'JACKET'

 
   ---------QUESTION 1: TOTAL REVENUE & TOTAL CUSTOMERS-------
SELECT SUM(TOTAL_PRICE) TOTAL_SALES FROM sales$;

SELECT COUNT(CUSTOMER_NAME) TOTAL_CUSTOMERS FROM customers$;
 

 ------------ QUESTION 2:MOST PURCHASED BY SEX AND TOTAL AMOUNT SPENT BY SEX-------


SELECT F.GENDER, SUM(F.TOTAL_PAYMENT) TOTAL_PAYMENT, MAX(F.MAX_PAYMENT) MAXIMUM_PAYMENT
FROM (SELECT C.GENDER,C.CUSTOMER_ID,   SUM(O.PAYMENT) TOTAL_PAYMENT,
MAX(O.PAYMENT) MAX_PAYMENT FROM customers$ C INNER JOIN orders$ O ON C.customer_id= O.customer_id
GROUP BY C.GENDER,C.CUSTOMER_ID)F GROUP BY F.GENDER;

 
 -------- QUESTION 3; TOTAL CUSTOMERS FROM EACH STATE---------

 SELECT "STATE", COUNT(CUSTOMER_NAME) 'NUMBER OF CUSTOMERS' FROM 
 customers$ GROUP BY "STATE" ORDER BY COUNT(CUSTOMER_NAME) DESC ;


 --------QUESTION 4: AMOUNT SPENT AND MAXIMUM AMOUNT FROM EACH STATE----------
	SELECT DISTINCT "STATE" FROM customers$;

	SELECT A."STATE",A.TRANSAC_NUMBER, A.TOTAL_AMOUNT, A.MAXIMUM_AMOUNT, A.CUSTOMER_NAME FROM
	(SELECT E."STATE",E.TRANSAC_NUMBER, E.TOTAL_AMOUNT, E.MAXIMUM_AMOUNT,E.CUSTOMER_ID, C.CUSTOMER_NAME FROM
	(SELECT DISTINCT W."STATE",W.TRANSAC_NUMBER, W.TOTAL_AMOUNT, W.MAXIMUM_AMOUNT,O.CUSTOMER_ID FROM 
	(SELECT Q."STATE",SUM(Q.TRANSAC_NUMBER) TRANSAC_NUMBER, SUM(Q.TOTAL_AMOUNT) TOTAL_AMOUNT,MAX(Q.MAXIMUM_PAYMENT) MAXIMUM_AMOUNT FROM
	(SELECT C."STATE",C.customer_id, COUNT(O.PAYMENT) TRANSAC_NUMBER,SUM(O.PAYMENT) TOTAL_AMOUNT, MAX(O.PAYMENT) 
	MAXIMUM_PAYMENT FROM customers$ C INNER JOIN orders$ O ON C.customer_id= O.customer_id
	GROUP BY C."STATE",C.customer_id)Q GROUP BY Q."STATE")W INNER JOIN ORDERS$ O  ON W.MAXIMUM_AMOUNT=O.PAYMENT)E
	 INNER JOIN CUSTOMERS$ C ON E.CUSTOMER_ID= C.CUSTOMER_ID)A ;
	

	
   ---------QUESTION 5: TOTAL AMOUNT AND MAXIMUM AMOUNT SPENT ON EACH PRODUCT TYPE---------
  SELECT DISTINCT Q.PRODUCT_TYPE,Q.QUANTITY, Q.TOTAL_PRICE, Q.MAXIMUM_PRICE,P.product_name FROM 
   (SELECT  P.PRODUCT_TYPE,COUNT(P.PRODUCT_TYPE) QUANTITY,SUM(P.PRICE*P.QUANTITY) TOTAL_PRICE, MAX(P.PRICE*P.QUANTITY)
   AS MAXIMUM_PRICE FROM products$ P GROUP BY P.PRODUCT_TYPE)Q INNER JOIN products$ P
    ON Q.MAXIMUM_PRICE= (P.QUANTITY*P.PRICE) ORDER BY product_type;



		 ----- QUESTION 6: AMOUNT EACH CUSTOMER SPENT-------
SELECT TOP 8 C.CUSTOMER_ID, C.CUSTOMER_NAME, SUM(O.PAYMENT)
 TOTAL_PAYMENT FROM customers$ C INNER JOIN orders$ O ON
  C.CUSTOMER_ID= O.CUSTOMER_ID GROUP BY C.CUSTOMER_ID, 
  C.CUSTOMER_NAME ORDER BY SUM(O.PAYMENT) DESC;

  SELECT TOP 8 C.CUSTOMER_ID, C.CUSTOMER_NAME, SUM(O.PAYMENT)
 TOTAL_PAYMENT FROM customers$ C INNER JOIN orders$ O ON
  C.CUSTOMER_ID= O.CUSTOMER_ID GROUP BY C.CUSTOMER_ID, 
  C.CUSTOMER_NAME ORDER BY SUM(O.PAYMENT) ASC;



  ----- QUESTION 7: WHICH PRODUCTS WERE SOLD THE MOST IN THE LAST TWO MONTH--------
  SELECT Q.PRODUCT_TYPE, SUM(Q.QUANTITY) TOTAL_SALE_QUANTITY, Q.MONTH FROM 
    (SELECT E.PRODUCT_ID,E.PRODUCT_TYPE,E.QUANTITY,E.ORDER_ID,MONTH(O.ORDER_DATE) 
	"MONTH" FROM  (SELECT P.PRODUCT_ID, P.PRODUCT_TYPE, S.ORDER_ID,SUM(S.QUANTITY) 
	 QUANTITY FROM products$ P INNER JOIN sales$ S ON P. PRODUCT_ID= S.PRODUCT_ID
	 GROUP BY P.PRODUCT_ID, P.PRODUCT_TYPE, S.ORDER_ID)E INNER JOIN orders$ O ON 
	 E.ORDER_ID= O.ORDER_ID)Q GROUP BY Q.PRODUCT_TYPE,Q.MONTH ORDER BY Q.MONTH DESC;


--------- QUESTION 8: TOTAL SALES BY MONTH-------

 SELECT Q.MONTH, SUM(Q.TOTAL_PRICE) MONTHLY_REVENUE FROM 
 (SELECT MONTH(O.ORDER_DATE) "MONTH", O.ORDER_ID, SUM(S.TOTAL_PRICE) TOTAL_PRICE FROM 
 orders$ O INNER JOIN sales$ S ON O.order_id= S.order_id GROUP BY  MONTH(O.ORDER_DATE),
 O.ORDER_ID)Q GROUP BY Q.MONTH ORDER BY Q.MONTH;




  --------QUESTION 9 : MONTH REVENUE ANALYSIS TO PRODUCT TYPE-----------
 
 SELECT  R.PRODUCT_TYPE, R.MONTH,R.PRODUCT_MONTHLY_REVENUE,T.MONTHLY_REVENUE,
 CONCAT(ROUND((R.PRODUCT_MONTHLY_REVENUE/T.MONTHLY_REVENUE)*100,2),'%') "% OF TOTAL REVENUE" 
  FROM
 (SELECT  W.MONTH,W.PRODUCT_TYPE, SUM(W.TOTAL_PRICE) PRODUCT_MONTHLY_REVENUE FROM 
  (SELECT Q.MONTH, Q.ORDER_ID,Q.PRODUCT_ID,Q.TOTAL_PRICE, P.PRODUCT_TYPE
   FROM (SELECT MONTH(O.ORDER_DATE) "MONTH", O.ORDER_ID, S.PRODUCT_ID,
   S.TOTAL_PRICE TOTAL_PRICE FROM orders$ O INNER JOIN sales$ S ON 
   O.order_id= S.order_id)Q INNER JOIN products$ P ON 
   Q.product_id= P.product_ID)W  GROUP BY W.MONTH,W.PRODUCT_TYPE)R 
   INNER JOIN
    ( SELECT Q.MONTH, SUM(Q.TOTAL_PRICE) MONTHLY_REVENUE FROM 
 (SELECT MONTH(O.ORDER_DATE) "MONTH", O.ORDER_ID, SUM(S.TOTAL_PRICE) TOTAL_PRICE FROM 
 orders$ O INNER JOIN sales$ S ON O.order_id= S.order_id GROUP BY  MONTH(O.ORDER_DATE),
 O.ORDER_ID)Q GROUP BY Q.MONTH )T ON R.MONTH= T.MONTH ORDER BY R.MONTH;



 
   --------- QUESTION 10:   MONTH REVENUE ANALYSIS TO STATE--------
 SELECT DISTINCT "STATE" FROM customers$;

  SELECT  R."STATE", R.MONTH,R.PRODUCT_MONTHLY_REVENUE,T.MONTHLY_REVENUE,
 CONCAT(ROUND((R.PRODUCT_MONTHLY_REVENUE/T.MONTHLY_REVENUE)*100,2),'%') "% OF TOTAL REVENUE" 
  FROM
 (SELECT  W.MONTH,W."STATE", SUM(W.TOTAL_PRICE) PRODUCT_MONTHLY_REVENUE FROM 
  (SELECT Q.MONTH, Q.customer_id,Q.PRODUCT_ID,Q.TOTAL_PRICE, C."STATE"
   FROM (SELECT MONTH(O.ORDER_DATE) "MONTH",O.order_id,O.customer_id, S.PRODUCT_ID,
   S.TOTAL_PRICE TOTAL_PRICE FROM orders$ O INNER JOIN sales$ S ON 
   O.order_id= S.order_id)Q INNER JOIN customers$ C ON 
   Q.customer_id= C.CUSTOMER_ID) W  GROUP BY W.MONTH,"STATE")R 
   INNER JOIN
    ( SELECT Q.MONTH, SUM(Q.TOTAL_PRICE) MONTHLY_REVENUE FROM 
 (SELECT MONTH(O.ORDER_DATE) "MONTH", O.ORDER_ID, SUM(S.TOTAL_PRICE) TOTAL_PRICE FROM 
 orders$ O INNER JOIN sales$ S ON O.order_id= S.order_id GROUP BY  MONTH(O.ORDER_DATE),
 O.ORDER_ID)Q GROUP BY Q.MONTH )T ON R.MONTH= T.MONTH ORDER BY R.MONTH;